#sudo systemctl start docker
#sudo docker compose up -d

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_admin
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    ports:
      - "${MYSQL_DOCKER_PORT}:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql