version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: p5-stock-app
    stdin_open: true
    tty: true
    working_dir: /workspaces/P5-stock
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:change_me_190184097095705698698148347@postgres:5432/p5stock
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: postgres_admin
    restart: always
    environment:
      POSTGRES_PASSWORD: change_me_190184097095705698698148347
      POSTGRES_DB: p5stock
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
