version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: p5-stock-app
    stdin_open: true
    tty: true
    working_dir: /workspaces/P5-stock
    environment:
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-p5stock}
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY:-supersecretkey}
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: postgres_admin
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-p5stock}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
    # ports:
    #   - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
